// <auto-generated />
using DAB.Webservice.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAB.Webservice.Migrations
{
    [DbContext(typeof(DABWebserviceContext))]
    [Migration("20211123001742_SeedInitialData")]
    partial class SeedInitialData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAB.Webservice.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Balance")
                        .HasColumnType("float");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pin")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Account");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 200.0,
                            Number = "1234567890123456",
                            Pin = "1234"
                        },
                        new
                        {
                            Id = 2,
                            Balance = 200.0,
                            Number = "2345678901234567",
                            Pin = "2345"
                        },
                        new
                        {
                            Id = 3,
                            Balance = 200.0,
                            Number = "3456789012345678",
                            Pin = "3456"
                        },
                        new
                        {
                            Id = 4,
                            Balance = 200.0,
                            Number = "4567890123456789",
                            Pin = "4567"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
