// <auto-generated />
using DAB.Webservice.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAB.Webservice.Migrations
{
    [DbContext(typeof(DABWebserviceContext))]
    partial class DABWebserviceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAB.Webservice.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthenticationTries")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<double>("Balance")
                        .HasColumnType("float");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pin")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Account");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthenticationTries = 0,
                            Balance = 50.0,
                            Number = "1234123412341234",
                            Pin = "1234"
                        },
                        new
                        {
                            Id = 2,
                            AuthenticationTries = 0,
                            Balance = 100.0,
                            Number = "3456345634563456",
                            Pin = "3456"
                        },
                        new
                        {
                            Id = 3,
                            AuthenticationTries = 0,
                            Balance = 150.0,
                            Number = "5678567856785678",
                            Pin = "5678"
                        },
                        new
                        {
                            Id = 4,
                            AuthenticationTries = 0,
                            Balance = 200.0,
                            Number = "7890789078907890",
                            Pin = "7890789078907890"
                        },
                        new
                        {
                            Id = 5,
                            AuthenticationTries = 0,
                            Balance = 250.0,
                            Number = "9012901290129012",
                            Pin = "9012"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
